source 'https://cdn.cocoapods.org/'
source 'https://github.com/expo/expo.git'

platform :ios, '15.1'

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), 'scripts/autolinking')
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), 'scripts/react_native_pods')

prepare_react_native_project!

target 'Homerunn' do
  use_expo_modules!

  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath], :hermes_enabled => true)

  # Add modular headers for Firebase pods that need it
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  post_install do |installer|
    react_native_post_install(installer)
  end
end